mybatis:
  type-aliases-package: com.itdreamworks.datamanage.entity
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.168.77:3306/bksrDB?useUnicode=true&characterEncoding=utf-8
    username: dba_user
    password: Test@163.com
debug: true